# Generated by Django 6.0.4 on 2026-04-28 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme zamanı')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya adı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Hatalı')], default='pending', max_length=20, verbose_name='Durum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Analiz',
                'verbose_name_plural': 'Analizler',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Ders')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Puan')),
                ('exam_date', models.DateField(verbose_name='Sınav tarihi')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='analysis.analysis', verbose_name='Analiz')),
            ],
            options={
                'verbose_name': 'Puan',
                'verbose_name_plural': 'Puanlar',
                'ordering': ['-exam_date', 'subject'],
            },
        ),
    ]
